### ISSUE TITLE
Cannot find module '/__enclose_io_memfs__/node_modules/express'

### ISSUE THREAD

**Issue by grkblood13** [pmq20/node-packer#100]
I'm trying to build a much larger project but I'm getting the error "Cannot find module '/__enclose_io_memfs__/node_modules/express'" on the very first line when I run my compiled code. To debug this I made my program as simple as possible. It's not a 1 line file called test.js with the following code:

var express = require(__dirname+'/node_modules/express');

I compiled it with `nodec test.js`  to produce a file called a.out.

When I run a.out I get the same error. To my understanding node-packer should be able to handle this. What am I missing?

**Comment by sido420** [comment]
did you find a solution for this?
