### ISSUE TITLE
when I exec nodec, error

### ISSUE THREAD

**Issue by ZhouBox** [pmq20/node-packer#126]
/__enclose_io_memfs__/local/lib/compiler.rb:105:in ``': No such file or directory - node (Errno::ENOENT)
	from /__enclose_io_memfs__/local/lib/compiler.rb:105:in `init_options'
	from /__enclose_io_memfs__/local/lib/compiler.rb:26:in `initialize'
	from /__enclose_io_memfs__/local/bin/nodec:153:in `new'
	from /__enclose_io_memfs__/local/bin/nodec:153:in `<main>'

**Comment by dkssn** [comment]
Got the same error.

Running on CentOS Linux release 7.5.1804 (Core)

**Comment by m8nky** [comment]
Same issue here at debian buster.
These are the packages installed:
apt install squashfs-tools gcc g++ clang python2.7 make

**Comment by m8nky** [comment]
Solved: Just install node or nodejs - e.g. from these sources: https://github.com/nodesource/distributions

**Comment by ZhouBox** [comment]
thanks
