### ISSUE TITLE
放弃维护了吗？

### ISSUE THREAD

**Issue by jakehu** [pmq20/node-packer#129]

**Comment by slee047** [comment]
不知道。但是你可以来我的 Repo 下载一样的 nodec，只是里面的 nodeJS 是 10.9.0 (Series10 的 branch) 或者 8.11.4 (master 的 branch)：

https://github.com/slee047/node-packer

**Comment by fengmk2** [comment]
@slee047 非常给力，大家可以转移到 @slee047 的代码库中。

**Comment by jakehu** [comment]
@slee047 给力

**Comment by jakehu** [comment]
@slee047 你好能咨询两个问题么？
我在项目文件夹下运行：
项目基于`egg`
```
ruby ../node-packer-1.6.0-8.11.4/bin/nodec node_modules/egg-bin/bin/egg-bin.js -r ./ ./
```
`rootDir`为当前目录
`ENTRANCE`也为当前目录
最后得到`a.out`执行文件
在执行`a.out`时出现下面错误:
```
module.js:549
    throw err;
    ^

Error: Cannot find module '/__enclose_io_memfs__'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:205:16)
    at bootstrap_node.js:643:3

```

**Comment by slee047** [comment]
@jakehu 不晓得，无法帮到。抱歉了。

**Comment by ferocknew** [comment]
作者还在吗

**Comment by slee047** [comment]
> @slee047 你好能咨询两个问题么？
> 我在项目文件夹下运行：
> 项目基于`egg`
> 
> ```
> ruby ../node-packer-1.6.0-8.11.4/bin/nodec node_modules/egg-bin/bin/egg-bin.js -r ./ ./
> ```
> 运行时配置项如下：
> 
> ```
> Node.js Compiler (nodec) v1.6.0
> - entrance: /home/jakehu/Web/siege
> - options: {:root=>"./", :npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64", :output=>"/home/jakehu/Web/siege/a.out", :tmpdir=>"/tmp/nodec"}
> ```
> `rootDir`为当前目录
> `ENTRANCE`也为当前目录
> 最后得到`a.out`执行文件
> 在执行`a.out`时出现下面错误:
> 
> ```
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module '/__enclose_io_memfs__'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:205:16)
>     at bootstrap_node.js:643:3
> ```
您好，请你试试看 https://github.com/slee047/node-packer/releases/tag/1.6.0-10.15.3-1

Node.js 10.15.3，我刚刚发现诸多 nodec 1.6.0-10.Y.Z 的之前都不能使用 Native module。刚刚修正了，不晓得是否对这个问题有帮助。

另外，请查看：
https://github.com/slee047/node-packer/issues/9

我偶然发现到你们俩都和 Egg.js 有关啊。

**Comment by VincentWuShiChao** [comment]
@slee047 我也是打包的egg项目，但是打包好之后，在当前项目根目录下执行a.out确实能启动项目，但是好像他依赖app文件夹，以及node_modules文件夹，但是要是依赖app文件夹的话，那打包的意义也就没有了，是有什么样的配置吗

**Comment by suntong** [comment]
> jakehu commented on Aug 17, 2018

Oh, I should have checked here first. So my last two days have been wasted then. So sad...
