### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by chintan39** [pmq20/node-packer#49]
Downloaded the latest version 1.1.0 on Ubuntu 14.04
When running the command I get below error

./nodec: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory

**Comment by m31271n** [comment]
The same issue.

**Comment by pmq20** [comment]
@chintan39 @m31271n I apologize. This is certainly my problem. Let me fix this as soon as possible. Thanks for reporting!

**Comment by pmq20** [comment]
Meanwhile if it was urgent you could workaround this via `sudo apt-get install libreadline5`

**Comment by pmq20** [comment]
@chintan39 @m31271n I have fixed this once and for all in nodec v1.2.0. Please try it and let me know if it works for you. Thanks!

https://github.com/pmq20/node-compiler/releases/tag/v1.2.0

|                       | Architecture |           Latest&#160;Stable                 |
|:---------------------:|:------------:|----------------------------------------------|
|      **Windows**      |    x86-64    | http://enclose.io/nodec/nodec-x64.zip        |
|       **macOS**       |    x86-64    | http://enclose.io/nodec/nodec-darwin-x64.gz  |
|       **Linux**       |    x86-64    | http://enclose.io/nodec/nodec-linux-x64.gz   |

**Comment by m31271n** [comment]
Awesome. It works. THX.

**Comment by m31271n** [comment]
Cann't wait make a node-compiler ebuild for my gentoo box. :rofl:

**Comment by chintan39** [comment]
Yes, it works now
